### ISSUE TITLE
Serving to iphone

### ISSUE THREAD

**Issue by anthony-duke** [met-office-lab/moc-vr#103]
Noticed when serving a new image, clients with iphone (5S and 6) doesn't always change to new image. Also, cross-hair doesn't always move with server machine movements. I'd say this is an issue about 75% of times. Not noticed this issue with android.

Occasionally when pasting in new image code, it is the same as the previous image. Restarting the 'server' seems a work around but obviously the client needs to look at the new session id

**Comment by tpowellmeto** [comment]
please check to see if this is still an issue - we redeployed the app earlier today with a new authentication system
