### ISSUE TITLE
Submitted confirmation message

### ISSUE THREAD

**Issue by anthony-duke** [met-office-lab/moc-vr#3]
Uploaded data on iphone, after pressing the upload button it took me to a blank catalogue page, so was unaware whether my upload was successful or not. Could do with a confirmation message to know that it was uploaded.

**Comment by tpowellmeto** [comment]
Seems to be a problem loading the images on iPhones.
See this link http://moc-vr.informaticslab.co.uk/?id=f25a461e-83bc-4d28-8358-ad76812906a1
Loads fine in some devices -
@tam203 was able to load the image on his android phone.

**Comment by tpowellmeto** [comment]
Looks like the problem actually lies with the browser 'Safari' not supporting the new `fetch` api.

**Comment by tpowellmeto** [comment]
add fetch polyfill
https://github.com/github/fetch

**Comment by tpowellmeto** [comment]
fix now on master
