### ISSUE TITLE
HUD display details

### ISSUE THREAD

**Issue by anthony-duke** [met-office-lab/moc-vr#39]
Temperature scales should be ordered so reading left to right Temp comes first then dewpoint.
Above temperature scales lable them "T" against temperature line and "Td" against dew point line.
Temperature line ideally black, depoint line ideally red.
Might need a solid colour box behind temperature scales to make sure data remains visible despite image in background.
Visibility >= 6KM should be displayed as integer units of KM. Visibilities <6km should be in metres to nearest 100 M.

Wind information to be displayed in barbs. Below is example of 'station circles'. VR display wouldn't need the circles but data to be displayed as barbs. Barbs indicate direction wind speed (pointing to where wind is going) and 'feathers' indicate wind speed rounded to nearest 5knots. Any gusts would be displayed as "G##" to the northeast of the barb.

![image](https://cloud.githubusercontent.com/assets/25768023/24149601/fb1f4532-0e3a-11e7-9822-2b8394d3c93b.png)

**Comment by tpowellmeto** [comment]
should 6000m visibility be displayed as '6000m' or '6km'

**Comment by anthony-duke** [comment]
6 KM
5000 M
Even the spaces between number and letter is noticeable to a forecaster

**Comment by tpowellmeto** [comment]
and caps or lower case?

**Comment by anthony-duke** [comment]
Caps

**Comment by tpowellmeto** [comment]
@anthony-duke what should the wind barbs look like with 0 wind?

**Comment by anthony-duke** [comment]
@tpowellmeto A circle, not filled 
O

**Comment by mo-ian-watkins** [comment]
If it's to be a station circle, can I ask you to double check your description of which way the wind barb points @anthony-duke ?

I'd have said the opposite, that the barb points in the direction the wind is coming **from**

**Comment by anthony-duke** [comment]
@mo-ian-watkins I guess it depends on your definition of 'points'.

We won't have a station circle but just the barb. If the barb is an arrow with feathers indicating the speed then the arrow-head will point in the direction the wind _is going_. e.g. "F" is a northerly wind (0 degrees), "L" a southerly wind (180)

**Comment by tpowellmeto** [comment]
now commited to master
