### ISSUE TITLE
504 Error when logging in

### ISSUE THREAD

**Issue by collegeonline** [met-office-lab/moc-vr#48]
I'm getting the following error when trying to login:

504 DNS look up failed

An error occured while trying to access the web site.

URL: http://docker-machine
Ref: WEBWIN/Web-proxy_http_error_page

**Comment by tpowellmeto** [comment]
Apologies, I was having a problem with some of the permissions whilst accessing the resources so was playing with the oauth2 configuration which is what gave you this error.

Try again now, it should be fixed. Also it should load thumbnails on iphones!
