### ISSUE TITLE
improve hud

### ISSUE THREAD

**Issue by tpowellmeto** [met-office-lab/moc-vr#53]
re-design
add wind gust value

**Comment by anthony-duke** [comment]
Can you please add time stamp of capture, from the upload info? HH:MM Don't include date. This is just for reference when looking at the LIDAR image. But put it with the temp and wind HUD not the LIDAR as it would look to crowded.
Also can you change the corporate lime green colours on the HUD? Maybe just black?

**Comment by tam203** [comment]
Close now #85 is done. Please raise new issues if there is additional work required.
