### ISSUE TITLE
User couldn't upload from android phone

### ISSUE THREAD

**Issue by anthony-duke** [met-office-lab/moc-vr#7]
Received a comment from one of the Mets, couldn't upload directly to the site from Android apparently:

From: Bland, Sophie 
Sent: 17 February 2017 11:26
To: Duke, Anthony
Subject: RE: 360 degree photos

Hi Ant,

The process was pretty simple. Although the ‘share’ icon is different on an Android phone:  
**I couldn’t upload the image from my phone either, so I had to email it to myself and upload it from the PC.**
Sophie

**Comment by tpowellmeto** [comment]
@tam203 was able to upload successfully from an android phone today.
I will close this issue for now based on that.

If it's still a problem please feel free to re-open but we will need more detail to reproduce the problem.
