### ISSUE TITLE
Upload page text tweek

### ISSUE THREAD

**Issue by anthony-duke** [met-office-lab/moc-vr#77]
Can you please add "Z" or "(Zulu)" after the date time fiel . Just so everyone is referring to zulu time which is also always the time axis of the lcbr/lidar screenshot.

**Comment by tam203** [comment]
Done. 
![image](https://cloud.githubusercontent.com/assets/1567535/26734462/feee708e-47b5-11e7-8016-666a1bd2f731.png)
